export const missingWords = [
  // ========== HSK 1 ==========
  { character: '杯子', pinyin: 'bei1 zi', english_definition: 'cup; glass', hsk_level: 1 },
  { character: '北京', pinyin: 'bei3 jing1', english_definition: 'Beijing', hsk_level: 1 },
  { character: '菜', pinyin: 'cai4', english_definition: 'dish; vegetable', hsk_level: 1 },
  { character: '出租车', pinyin: 'chu1 zu1 che1', english_definition: 'taxi', hsk_level: 1 },
  { character: '打电话', pinyin: 'da3 dian4 hua4', english_definition: 'make a phone call', hsk_level: 1 },
  { character: '地方', pinyin: 'di4 fang', english_definition: 'place', hsk_level: 1 },
  { character: '电视', pinyin: 'dian4 shi4', english_definition: 'television; TV', hsk_level: 1 },
  { character: '电影', pinyin: 'dian4 ying3', english_definition: 'movie; film', hsk_level: 1 },
  { character: '东西', pinyin: 'dong1 xi', english_definition: 'thing; stuff', hsk_level: 1 },
  { character: '多少', pinyin: 'duo1 shao3', english_definition: 'how many; how much', hsk_level: 1 },
  { character: '饭馆', pinyin: 'fan4 guan3', english_definition: 'restaurant', hsk_level: 1 },
  { character: '飞机', pinyin: 'fei1 ji1', english_definition: 'airplane', hsk_level: 1 },
  { character: '个', pinyin: 'ge4', english_definition: 'general measure word', hsk_level: 1 },
  { character: '工作', pinyin: 'gong1 zuo4', english_definition: 'work; job', hsk_level: 1 },
  { character: '狗', pinyin: 'gou3', english_definition: 'dog', hsk_level: 1 },
  { character: '好吃', pinyin: 'hao3 chi1', english_definition: 'delicious', hsk_level: 1 },
  { character: '号', pinyin: 'hao4', english_definition: 'day of month; number', hsk_level: 1 },
  { character: '后面', pinyin: 'hou4 mian', english_definition: 'behind; back', hsk_level: 1 },
  { character: '看见', pinyin: 'kan4 jian4', english_definition: 'to see', hsk_level: 1 },
  { character: '块', pinyin: 'kuai4', english_definition: 'piece; yuan (money)', hsk_level: 1 },
  { character: '老师', pinyin: 'lao3 shi1', english_definition: 'teacher', hsk_level: 1 },
  { character: '两', pinyin: 'liang3', english_definition: 'two (of something)', hsk_level: 1 },
  { character: '零', pinyin: 'ling2', english_definition: 'zero', hsk_level: 1 },
  { character: '马', pinyin: 'ma3', english_definition: 'horse', hsk_level: 1 },
  { character: '猫', pinyin: 'mao1', english_definition: 'cat', hsk_level: 1 },
  { character: '没关系', pinyin: 'mei2 guan1 xi', english_definition: "it doesn't matter; it's ok", hsk_level: 1 },
  { character: '没有', pinyin: 'mei2 you3', english_definition: "don't have; there is not", hsk_level: 1 },
  { character: '名字', pinyin: 'ming2 zi', english_definition: 'name', hsk_level: 1 },
  { character: '女人', pinyin: 'nv3 ren2', english_definition: 'woman', hsk_level: 1 },
  { character: '朋友', pinyin: 'peng2 you', english_definition: 'friend', hsk_level: 1 },
  { character: '钱', pinyin: 'qian2', english_definition: 'money', hsk_level: 1 },
  { character: '前面', pinyin: 'qian2 mian', english_definition: 'in front; ahead', hsk_level: 1 },
  { character: '人', pinyin: 'ren2', english_definition: 'person', hsk_level: 1 },
  { character: '认识', pinyin: 'ren4 shi', english_definition: 'to know (someone)', hsk_level: 1 },
  { character: '什么', pinyin: 'shen2 me', english_definition: 'what', hsk_level: 1 },
  { character: '生日', pinyin: 'sheng1 ri4', english_definition: 'birthday', hsk_level: 1 },
  { character: '时候', pinyin: 'shi2 hou', english_definition: 'time; moment', hsk_level: 1 },
  { character: '书', pinyin: 'shu1', english_definition: 'book', hsk_level: 1 },
  { character: '岁', pinyin: 'sui4', english_definition: 'years old', hsk_level: 1 },
  { character: '同学', pinyin: 'tong2 xue2', english_definition: 'classmate', hsk_level: 1 },
  { character: '我们', pinyin: 'wo3 men', english_definition: 'we; us', hsk_level: 1 },
  { character: '西瓜', pinyin: 'xi1 gua1', english_definition: 'watermelon', hsk_level: 1 },
  { character: '西面', pinyin: 'xi1 mian', english_definition: 'west side', hsk_level: 1 },
  { character: '先生', pinyin: 'xian1 sheng', english_definition: 'Mr.; husband', hsk_level: 1 },
  { character: '小姐', pinyin: 'xiao3 jie', english_definition: 'Miss; young lady', hsk_level: 1 },
  { character: '些', pinyin: 'xie1', english_definition: 'some; a few', hsk_level: 1 },
  { character: '学生', pinyin: 'xue2 sheng', english_definition: 'student', hsk_level: 1 },
  { character: '衣服', pinyin: 'yi1 fu', english_definition: 'clothes', hsk_level: 1 },
  { character: '医生', pinyin: 'yi1 sheng1', english_definition: 'doctor', hsk_level: 1 },
  { character: '椅子', pinyin: 'yi3 zi', english_definition: 'chair', hsk_level: 1 },
  { character: '已经', pinyin: 'yi3 jing1', english_definition: 'already', hsk_level: 1 },
  { character: '因为', pinyin: 'yin1 wei4', english_definition: 'because', hsk_level: 1 },
  { character: '怎么', pinyin: 'zen3 me', english_definition: 'how', hsk_level: 1 },
  { character: '怎么样', pinyin: 'zen3 me yang4', english_definition: 'how about; how is it', hsk_level: 1 },
  { character: '住', pinyin: 'zhu4', english_definition: 'to live; to stay', hsk_level: 1 },
  { character: '桌子', pinyin: 'zhuo1 zi', english_definition: 'table; desk', hsk_level: 1 },

  // ========== HSK 2 ==========
  { character: '百', pinyin: 'bai3', english_definition: 'hundred', hsk_level: 2 },
  { character: '报纸', pinyin: 'bao4 zhi3', english_definition: 'newspaper', hsk_level: 2 },
  { character: '宾馆', pinyin: 'bin1 guan3', english_definition: 'hotel; guesthouse', hsk_level: 2 },
  { character: '唱歌', pinyin: 'chang4 ge1', english_definition: 'to sing', hsk_level: 2 },
  { character: '次', pinyin: 'ci4', english_definition: 'order; time (occurrence)', hsk_level: 2 },
  { character: '打篮球', pinyin: 'da3 lan2 qiu2', english_definition: 'play basketball', hsk_level: 2 },
  { character: '大家', pinyin: 'da4 jia1', english_definition: 'everyone', hsk_level: 2 },
  { character: '但是', pinyin: 'dan4 shi4', english_definition: 'but; however', hsk_level: 2 },
  { character: '蛋糕', pinyin: 'dan4 gao1', english_definition: 'cake', hsk_level: 2 },
  { character: '当然', pinyin: 'dang1 ran2', english_definition: 'of course', hsk_level: 2 },
  { character: '动物', pinyin: 'dong4 wu4', english_definition: 'animal', hsk_level: 2 },
  { character: '多么', pinyin: 'duo1 me', english_definition: 'how (wonderful, etc.)', hsk_level: 2 },
  { character: '发现', pinyin: 'fa1 xian4', english_definition: 'to discover; to find', hsk_level: 2 },
  { character: '房间', pinyin: 'fang2 jian1', english_definition: 'room', hsk_level: 2 },
  { character: '非常', pinyin: 'fei1 chang2', english_definition: 'very; extremely', hsk_level: 2 },
  { character: '附近', pinyin: 'fu4 jin4', english_definition: 'nearby; vicinity', hsk_level: 2 },
  { character: '刚才', pinyin: 'gang1 cai2', english_definition: 'just now', hsk_level: 2 },
  { character: '告诉', pinyin: 'gao4 su', english_definition: 'to tell', hsk_level: 2 },
  { character: '公共汽车', pinyin: 'gong1 gong4 qi4 che1', english_definition: 'bus', hsk_level: 2 },
  { character: '公司', pinyin: 'gong1 si1', english_definition: 'company; corporation', hsk_level: 2 },
  { character: '贵', pinyin: 'gui4', english_definition: 'expensive', hsk_level: 2 },
  { character: '还是', pinyin: 'hai2 shi4', english_definition: 'still; or (preference)', hsk_level: 2 },
  { character: '孩子', pinyin: 'hai2 zi', english_definition: 'child', hsk_level: 2 },
  { character: '好像', pinyin: 'hao3 xiang4', english_definition: 'seems like; as if', hsk_level: 2 },
  { character: '换', pinyin: 'huan4', english_definition: 'to exchange; to change', hsk_level: 2 },
  { character: '回答', pinyin: 'hui2 da2', english_definition: 'to answer; to reply', hsk_level: 2 },
  { character: '极', pinyin: 'ji2', english_definition: 'extremely', hsk_level: 2 },
  { character: '季节', pinyin: 'ji4 jie2', english_definition: 'season', hsk_level: 2 },
  { character: '检查', pinyin: 'jian3 cha2', english_definition: 'to check; to inspect', hsk_level: 2 },
  { character: '教室', pinyin: 'jiao4 shi4', english_definition: 'classroom', hsk_level: 2 },
  { character: '介绍', pinyin: 'jie4 shao4', english_definition: 'to introduce', hsk_level: 2 },
  { character: '经常', pinyin: 'jing1 chang2', english_definition: 'often; frequently', hsk_level: 2 },
  { character: '觉得', pinyin: 'jue2 de', english_definition: 'to think; to feel', hsk_level: 2 },
  { character: '开始', pinyin: 'kai1 shi3', english_definition: 'to start; to begin', hsk_level: 2 },
  { character: '可能', pinyin: 'ke3 neng2', english_definition: 'maybe; possible', hsk_level: 2 },
  { character: '可以', pinyin: 'ke3 yi3', english_definition: 'can; may; okay', hsk_level: 2 },
  { character: '课', pinyin: 'ke4', english_definition: 'class; lesson', hsk_level: 2 },
  { character: '空调', pinyin: 'kong1 tiao2', english_definition: 'air conditioner', hsk_level: 2 },
  { character: '筷子', pinyin: 'kuai4 zi', english_definition: 'chopsticks', hsk_level: 2 },
  { character: '旅游', pinyin: 'lv3 you2', english_definition: 'to travel', hsk_level: 2 },
  { character: '明白', pinyin: 'ming2 bai', english_definition: 'to understand; clear', hsk_level: 2 },
  { character: '拿', pinyin: 'na2', english_definition: 'to take; to hold', hsk_level: 2 },
  { character: '男人', pinyin: 'nan2 ren2', english_definition: 'man', hsk_level: 2 },
  { character: '那么', pinyin: 'na4 me', english_definition: 'then; so; like that', hsk_level: 2 },
  { character: '难看', pinyin: 'nan2 kan4', english_definition: 'ugly', hsk_level: 2 },
  { character: '努力', pinyin: 'nu3 li4', english_definition: 'diligent; hardworking', hsk_level: 2 },
  { character: '爬山', pinyin: 'pa2 shan1', english_definition: 'to climb a mountain', hsk_level: 2 },
  { character: '跑步', pinyin: 'pao3 bu4', english_definition: 'to run; to jog', hsk_level: 2 },
  { character: '便宜', pinyin: 'pian2 yi', english_definition: 'cheap', hsk_level: 2 },
  { character: '平时', pinyin: 'ping2 shi2', english_definition: 'usually; normally', hsk_level: 2 },
  { character: '铅笔', pinyin: 'qian1 bi3', english_definition: 'pencil', hsk_level: 2 },
  { character: '亲爱', pinyin: 'qin1 ai4', english_definition: 'dear', hsk_level: 2 },
  { character: '清楚', pinyin: 'qing1 chu', english_definition: 'clear; clearly', hsk_level: 2 },
  { character: '去年', pinyin: 'qu4 nian2', english_definition: 'last year', hsk_level: 2 },
  { character: '认为', pinyin: 'ren4 wei2', english_definition: 'to think; to consider', hsk_level: 2 },
  { character: '容易', pinyin: 'rong2 yi4', english_definition: 'easy', hsk_level: 2 },
  { character: '如果', pinyin: 'ru2 guo3', english_definition: 'if', hsk_level: 2 },
  { character: '伞', pinyin: 'san3', english_definition: 'umbrella', hsk_level: 2 },
  { character: '身体', pinyin: 'shen1 ti3', english_definition: 'body; health', hsk_level: 2 },
  { character: '生病', pinyin: 'sheng1 bing4', english_definition: 'to get sick', hsk_level: 2 },
  { character: '生气', pinyin: 'sheng1 qi4', english_definition: 'to be angry', hsk_level: 2 },
  { character: '声音', pinyin: 'sheng1 yin1', english_definition: 'sound; voice', hsk_level: 2 },
  { character: '时间', pinyin: 'shi2 jian1', english_definition: 'time', hsk_level: 2 },
  { character: '事情', pinyin: 'shi4 qing', english_definition: 'matter; affair', hsk_level: 2 },
  { character: '手表', pinyin: 'shou3 biao3', english_definition: 'wrist watch', hsk_level: 2 },
  { character: '手机', pinyin: 'shou3 ji1', english_definition: 'mobile phone', hsk_level: 2 },
  { character: '说话', pinyin: 'shuo1 hua4', english_definition: 'to speak; to talk', hsk_level: 2 },
  { character: '虽然', pinyin: 'sui1 ran2', english_definition: 'although', hsk_level: 2 },
  { character: '踢足球', pinyin: 'ti1 zu2 qiu2', english_definition: 'to play soccer', hsk_level: 2 },
  { character: '题', pinyin: 'ti2', english_definition: 'question; topic', hsk_level: 2 },
  { character: '跳舞', pinyin: 'tiao4 wu3', english_definition: 'to dance', hsk_level: 2 },
  { character: '完', pinyin: 'wan2', english_definition: 'to finish', hsk_level: 2 },
  { character: '玩', pinyin: 'wan2', english_definition: 'to play; to have fun', hsk_level: 2 },
  { character: '为什么', pinyin: 'wei4 shen2 me', english_definition: 'why', hsk_level: 2 },
  { character: '位置', pinyin: 'wei4 zhi', english_definition: 'position; location', hsk_level: 2 },
  { character: '文化', pinyin: 'wen2 hua4', english_definition: 'culture', hsk_level: 2 },
  { character: '问', pinyin: 'wen4', english_definition: 'to ask', hsk_level: 2 },
  { character: '问题', pinyin: 'wen4 ti2', english_definition: 'question; problem', hsk_level: 2 },
  { character: '希望', pinyin: 'xi1 wang4', english_definition: 'to hope; to wish', hsk_level: 2 },
  { character: '洗手间', pinyin: 'xi3 shou3 jian1', english_definition: 'restroom; bathroom', hsk_level: 2 },
  { character: '喜欢', pinyin: 'xi3 huan', english_definition: 'to like', hsk_level: 2 },
  { character: '新闻', pinyin: 'xin1 wen2', english_definition: 'news', hsk_level: 2 },
  { character: '行李箱', pinyin: 'xing2 li3 xiang1', english_definition: 'suitcase; luggage', hsk_level: 2 },
  { character: '选择', pinyin: 'xuan3 ze2', english_definition: 'to choose; choice', hsk_level: 2 },
  { character: '颜色', pinyin: 'yan2 se4', english_definition: 'color', hsk_level: 2 },
  { character: '音乐', pinyin: 'yin1 yue4', english_definition: 'music', hsk_level: 2 },
  { character: '因为', pinyin: 'yin1 wei4', english_definition: 'because', hsk_level: 2 },
  { character: '遇到', pinyin: 'yu4 dao4', english_definition: 'to meet; to encounter', hsk_level: 2 },
  { character: '元', pinyin: 'yuan2', english_definition: 'yuan (Chinese monetary unit)', hsk_level: 2 },
  { character: '运动', pinyin: 'yun4 dong4', english_definition: 'sports; exercise', hsk_level: 2 },
  { character: '正在', pinyin: 'zheng4 zai4', english_definition: 'in the process of', hsk_level: 2 },
  { character: '重要', pinyin: 'zhong4 yao4', english_definition: 'important', hsk_level: 2 },
  { character: '周末', pinyin: 'zhou1 mo4', english_definition: 'weekend', hsk_level: 2 },
  { character: '注意', pinyin: 'zhu4 yi4', english_definition: 'to pay attention', hsk_level: 2 },
  { character: '自行车', pinyin: 'zi4 xing2 che1', english_definition: 'bicycle', hsk_level: 2 },
  { character: '最', pinyin: 'zui4', english_definition: 'most; -est (superlative)', hsk_level: 2 },

  // ========== HSK 3 ==========
  { character: '按时', pinyin: 'an4 shi2', english_definition: 'on time; punctually', hsk_level: 3 },
  { character: '班', pinyin: 'ban1', english_definition: 'class; shift', hsk_level: 3 },
  { character: '办法', pinyin: 'ban4 fa3', english_definition: 'method; way', hsk_level: 3 },
  { character: '办公室', pinyin: 'ban4 gong1 shi4', english_definition: 'office', hsk_level: 3 },
  { character: '帮忙', pinyin: 'bang1 mang2', english_definition: 'to help; to lend a hand', hsk_level: 3 },
  { character: '包', pinyin: 'bao1', english_definition: 'bag; to wrap', hsk_level: 3 },
  { character: '比较', pinyin: 'bi3 jiao4', english_definition: 'relatively; to compare', hsk_level: 3 },
  { character: '比赛', pinyin: 'bi3 sai4', english_definition: 'competition; match', hsk_level: 3 },
  { character: '必须', pinyin: 'bi4 xu1', english_definition: 'must; have to', hsk_level: 3 },
  { character: '表示', pinyin: 'biao3 shi4', english_definition: 'to express; to indicate', hsk_level: 3 },
  { character: '表演', pinyin: 'biao3 yan3', english_definition: 'performance; to perform', hsk_level: 3 },
  { character: '别人', pinyin: 'bie2 ren', english_definition: 'other people; others', hsk_level: 3 },
  { character: '冰箱', pinyin: 'bing1 xiang1', english_definition: 'refrigerator', hsk_level: 3 },
  { character: '菜单', pinyin: 'cai4 dan1', english_definition: 'menu', hsk_level: 3 },
  { character: '参加', pinyin: 'can1 jia1', english_definition: 'to participate; to join', hsk_level: 3 },
  { character: '草', pinyin: 'cao3', english_definition: 'grass', hsk_level: 3 },
  { character: '层', pinyin: 'ceng2', english_definition: 'floor; layer', hsk_level: 3 },
  { character: '差', pinyin: 'cha4', english_definition: 'poor; to differ', hsk_level: 3 },
  { character: '超市', pinyin: 'chao1 shi4', english_definition: 'supermarket', hsk_level: 3 },
  { character: '衬衫', pinyin: 'chen4 shan1', english_definition: 'shirt', hsk_level: 3 },
  { character: '成绩', pinyin: 'cheng2 ji4', english_definition: 'score; grade; achievement', hsk_level: 3 },
  { character: '迟到', pinyin: 'chi2 dao4', english_definition: 'to arrive late', hsk_level: 3 },
  { character: '除了', pinyin: 'chu2 le', english_definition: 'except; besides', hsk_level: 3 },
  { character: '厨房', pinyin: 'chu2 fang2', english_definition: 'kitchen', hsk_level: 3 },
  { character: '聪明', pinyin: 'cong1 ming', english_definition: 'intelligent; clever', hsk_level: 3 },
  { character: '打扫', pinyin: 'da3 sao3', english_definition: 'to clean', hsk_level: 3 },
  { character: '打算', pinyin: 'da3 suan', english_definition: 'to plan; intention', hsk_level: 3 },
  { character: '担心', pinyin: 'dan1 xin1', english_definition: 'to worry', hsk_level: 3 },
  { character: '蛋', pinyin: 'dan4', english_definition: 'egg', hsk_level: 3 },
  { character: '地图', pinyin: 'di4 tu2', english_definition: 'map', hsk_level: 3 },
  { character: '第', pinyin: 'di4', english_definition: 'prefix for ordinal numbers', hsk_level: 3 },
  { character: '点', pinyin: 'dian3', english_definition: 'o\'clock; point; dot', hsk_level: 3 },
  { character: '电梯', pinyin: 'dian4 ti1', english_definition: 'elevator', hsk_level: 3 },
  { character: '电子邮件', pinyin: 'dian4 zi3 you2 jian4', english_definition: 'email', hsk_level: 3 },
  { character: '动', pinyin: 'dong4', english_definition: 'to move', hsk_level: 3 },
  { character: '堵车', pinyin: 'du3 che1', english_definition: 'traffic jam', hsk_level: 3 },
  { character: '锻炼', pinyin: 'duan4 lian4', english_definition: 'to exercise; to work out', hsk_level: 3 },
  { character: '发烧', pinyin: 'fa1 shao1', english_definition: 'to have a fever', hsk_level: 3 },
  { character: '方便', pinyin: 'fang1 bian4', english_definition: 'convenient', hsk_level: 3 },
  { character: '放心', pinyin: 'fang4 xin1', english_definition: 'to reassure; to set one\'s mind at ease', hsk_level: 3 },
  { character: '感冒', pinyin: 'gan3 mao4', english_definition: 'to catch a cold', hsk_level: 3 },
  { character: '感兴趣', pinyin: 'gan4 xing4 qu4', english_definition: 'to be interested', hsk_level: 3 },
  { character: '刚', pinyin: 'gang1', english_definition: 'just; barely', hsk_level: 3 },
  { character: '各种', pinyin: 'ge4 zhong3', english_definition: 'all kinds of', hsk_level: 3 },
  { character: '根据', pinyin: 'gen1 ju4', english_definition: 'according to; basis', hsk_level: 3 },
  { character: '公园', pinyin: 'gong1 yuan2', english_definition: 'park', hsk_level: 3 },
  { character: '共', pinyin: 'gong4', english_definition: 'altogether; total', hsk_level: 3 },
  { character: '故事', pinyin: 'gu4 shi', english_definition: 'story', hsk_level: 3 },
  { character: '刮风', pinyin: 'gua1 feng1', english_definition: 'to be windy', hsk_level: 3 },
  { character: '关系', pinyin: 'guan1 xi', english_definition: 'relationship; connection', hsk_level: 3 },
  { character: '关心', pinyin: 'guan1 xin1', english_definition: 'to care about', hsk_level: 3 },
  { character: '管', pinyin: 'guan3', english_definition: 'to manage; to bother about', hsk_level: 3 },
  { character: '国际', pinyin: 'guo2 ji4', english_definition: 'international', hsk_level: 3 },
  { character: '过去', pinyin: 'guo4 qu4', english_definition: 'past; to go over', hsk_level: 3 },
  { character: '害怕', pinyin: 'hai4 pa4', english_definition: 'to be afraid', hsk_level: 3 },
  { character: '寒假', pinyin: 'han2 jia4', english_definition: 'winter vacation', hsk_level: 3 },
  { character: '黑板', pinyin: 'hei1 ban3', english_definition: 'blackboard', hsk_level: 3 },
  { character: '后来', pinyin: 'hou4 lai2', english_definition: 'later; afterwards', hsk_level: 3 },
  { character: '互联网', pinyin: 'hu4 lian2 wang3', english_definition: 'internet', hsk_level: 3 },
  { character: '护士', pinyin: 'hu4 shi', english_definition: 'nurse', hsk_level: 3 },
  { character: '环境', pinyin: 'huan2 jing4', english_definition: 'environment', hsk_level: 3 },
  { character: '换', pinyin: 'huan4', english_definition: 'to exchange; to change', hsk_level: 3 },
  { character: '回来', pinyin: 'hui2 lai', english_definition: 'to come back', hsk_level: 3 },
  { character: '会议', pinyin: 'hui4 yi4', english_definition: 'meeting; conference', hsk_level: 3 },
  { character: '机会', pinyin: 'ji1 hui4', english_definition: 'opportunity; chance', hsk_level: 3 },
  { character: '积极', pinyin: 'ji1 ji2', english_definition: 'positive; active', hsk_level: 3 },
  { character: '即使', pinyin: 'ji2 shi3', english_definition: 'even if', hsk_level: 3 },
  { character: '记得', pinyin: 'ji4 de', english_definition: 'to remember', hsk_level: 3 },
  { character: '加油', pinyin: 'jia1 you2', english_definition: "to refuel; go! come on!", hsk_level: 3 },
  { character: '简单', pinyin: 'jian3 dan1', english_definition: 'simple', hsk_level: 3 },
  { character: '见面', pinyin: 'jian4 mian4', english_definition: 'to meet (someone)', hsk_level: 3 },
  { character: '结婚', pinyin: 'jie2 hun1', english_definition: 'to get married', hsk_level: 3 },
  { character: '结束', pinyin: 'jie2 shu4', english_definition: 'to end; to finish', hsk_level: 3 },
  { character: '解决', pinyin: 'jie3 jue2', english_definition: 'to solve; to resolve', hsk_level: 3 },
  { character: '进来', pinyin: 'jin4 lai', english_definition: 'to come in', hsk_level: 3 },
  { character: '经历', pinyin: 'jing1 li4', english_definition: 'experience; to experience', hsk_level: 3 },
  { character: '经验', pinyin: 'jing1 yan4', english_definition: 'experience', hsk_level: 3 },
  { character: '景色', pinyin: 'jing3 se4', english_definition: 'scenery; view', hsk_level: 3 },
  { character: '举行', pinyin: 'ju3 xing2', english_definition: 'to hold (a meeting/event)', hsk_level: 3 },
  { character: '句子', pinyin: 'ju4 zi', english_definition: 'sentence', hsk_level: 3 },
  { character: '决定', pinyin: 'jue2 ding4', english_definition: 'to decide; decision', hsk_level: 3 },
  { character: '考虑', pinyin: 'kao3 lv4', english_definition: 'to consider; to think over', hsk_level: 3 },
  { character: '客人', pinyin: 'ke4 ren', english_definition: 'guest', hsk_level: 3 },
  { character: '空气', pinyin: 'kong1 qi4', english_definition: 'air', hsk_level: 3 },
  { character: '口语', pinyin: 'kou3 yu3', english_definition: 'spoken language', hsk_level: 3 },
  { character: '裤子', pinyin: 'ku4 zi', english_definition: 'pants; trousers', hsk_level: 3 },
  { character: '快乐', pinyin: 'kuai4 le4', english_definition: 'happy; joyful', hsk_level: 3 },
  { character: '来不及', pinyin: 'lai2 bu4 ji2', english_definition: "there's not enough time", hsk_level: 3 },
  { character: '来得及', pinyin: 'lai2 de2 ji2', english_definition: "there's still time", hsk_level: 3 },
  { character: '来自', pinyin: 'lai2 zi4', english_definition: 'to come from', hsk_level: 3 },
  { character: '离开', pinyin: 'li2 kai1', english_definition: 'to leave', hsk_level: 3 },
  { character: '礼貌', pinyin: 'li3 mao4', english_definition: 'politeness; manners', hsk_level: 3 },
  { character: '礼物', pinyin: 'li3 wu4', english_definition: 'gift; present', hsk_level: 3 },
  { character: '厉害', pinyin: 'li4 hai', english_definition: 'terrific; severe; formidable', hsk_level: 3 },
  { character: '历史', pinyin: 'li4 shi3', english_definition: 'history', hsk_level: 3 },
  { character: '联系', pinyin: 'lian2 xi4', english_definition: 'to contact; connection', hsk_level: 3 },
  { character: '楼梯', pinyin: 'lou2 ti1', english_definition: 'stairs', hsk_level: 3 },
  { character: '旅行', pinyin: 'lv3 xing2', english_definition: 'to travel', hsk_level: 3 },
  { character: '马路', pinyin: 'ma3 lu4', english_definition: 'road; street', hsk_level: 3 },
  { character: '麻烦', pinyin: 'ma2 fan', english_definition: 'troublesome; to bother', hsk_level: 3 },
  { character: '满意', pinyin: 'man3 yi4', english_definition: 'satisfied', hsk_level: 3 },
  { character: '毛巾', pinyin: 'mao2 jin1', english_definition: 'towel', hsk_level: 3 },
  { character: '每次', pinyin: 'mei3 ci4', english_definition: 'every time', hsk_level: 3 },
  { character: '美丽', pinyin: 'mei3 li4', english_definition: 'beautiful', hsk_level: 3 },
  { character: '门口', pinyin: 'men2 kou3', english_definition: 'doorway; entrance', hsk_level: 3 },
  { character: '面试', pinyin: 'mian4 shi4', english_definition: 'interview', hsk_level: 3 },
  { character: '明显', pinyin: 'ming2 xian3', english_definition: 'obvious; evident', hsk_level: 3 },
  { character: '拿来', pinyin: 'na2 lai', english_definition: 'to bring (here)', hsk_level: 3 },
  { character: '男朋友', pinyin: 'nan2 peng2 you', english_definition: 'boyfriend', hsk_level: 3 },
  { character: '难道', pinyin: 'nan2 dao4', english_definition: "could it be that...", hsk_level: 3 },
  { character: '难忘', pinyin: 'nan2 wang4', english_definition: 'unforgettable', hsk_level: 3 },
  { character: '年级', pinyin: 'nian2 ji2', english_definition: 'grade; year level', hsk_level: 3 },
  { character: '年龄', pinyin: 'nian2 ling2', english_definition: 'age (of a person)', hsk_level: 3 },
  { character: '偶尔', pinyin: 'ou3 er3', english_definition: 'occasionally', hsk_level: 3 },
  { character: '排队', pinyin: 'pai2 dui4', english_definition: 'to line up; to queue', hsk_level: 3 },
  { character: '判断', pinyin: 'pan4 duan4', english_definition: 'to judge; judgment', hsk_level: 3 },
  { character: '旁边', pinyin: 'pang2 bian1', english_definition: 'beside; nearby', hsk_level: 3 },
  { character: '批评', pinyin: 'pi1 ping2', english_definition: 'to criticize; criticism', hsk_level: 3 },
  { character: '其次', pinyin: 'qi2 ci4', english_definition: 'next; secondly', hsk_level: 3 },
  { character: '其实', pinyin: 'qi2 shi2', english_definition: 'actually; in fact', hsk_level: 3 },
  { character: '其中', pinyin: 'qi2 zhong1', english_definition: 'among them', hsk_level: 3 },
  { character: '起床', pinyin: 'qi3 chuang2', english_definition: 'to get up (from bed)', hsk_level: 3 },
  { character: '起来', pinyin: 'qi3 lai', english_definition: 'to get up; to rise', hsk_level: 3 },
  { character: '轻松', pinyin: 'qing1 song1', english_definition: 'light; relaxed', hsk_level: 3 },
  { character: '情况', pinyin: 'qing2 kuang4', english_definition: 'situation; condition', hsk_level: 3 },
  { character: '请假', pinyin: 'qing3 jia4', english_definition: 'to ask for leave', hsk_level: 3 },
  { character: '区别', pinyin: 'qu1 bie2', english_definition: 'difference; to distinguish', hsk_level: 3 },
  { character: '缺点', pinyin: 'que1 dian3', english_definition: 'shortcoming; weakness', hsk_level: 3 },
  { character: '然后', pinyin: 'ran2 hou4', english_definition: 'then; after that', hsk_level: 3 },
  { character: '热情', pinyin: 're4 qing2', english_definition: 'passion; enthusiasm', hsk_level: 3 },
  { character: '人们', pinyin: 'ren2 men', english_definition: 'people', hsk_level: 3 },
  { character: '认真', pinyin: 'ren4 zhen1', english_definition: 'serious; conscientious', hsk_level: 3 },
  { character: '日记', pinyin: 'ri4 ji4', english_definition: 'diary; journal', hsk_level: 3 },
  { character: '身份证', pinyin: 'shen1 fen4 zheng4', english_definition: 'ID card', hsk_level: 3 },
  { character: '什么时候', pinyin: 'shen2 me shi2 hou', english_definition: 'when', hsk_level: 3 },
  { character: '使', pinyin: 'shi3', english_definition: 'to make; to cause', hsk_level: 3 },
  { character: '是否', pinyin: 'shi4 fou3', english_definition: 'whether or not', hsk_level: 3 },
  { character: '熟悉', pinyin: 'shu2 xi1', english_definition: 'to be familiar with', hsk_level: 3 },
  { character: '数学', pinyin: 'shu4 xue2', english_definition: 'mathematics', hsk_level: 3 },
  { character: '说明', pinyin: 'shuo1 ming2', english_definition: 'to explain; explanation', hsk_level: 3 },
  { character: '随便', pinyin: 'sui2 bian4', english_definition: 'casual; as one pleases', hsk_level: 3 },
  { character: '随着', pinyin: 'sui2 zhe', english_definition: 'along with', hsk_level: 3 },
  { character: '弹钢琴', pinyin: 'tan2 gang1 qin2', english_definition: 'to play the piano', hsk_level: 3 },
  { character: '特别', pinyin: 'te4 bie2', english_definition: 'special; especially', hsk_level: 3 },
  { character: '体育', pinyin: 'ti3 yu4', english_definition: 'physical education; sports', hsk_level: 3 },
  { character: '天气', pinyin: 'tian1 qi4', english_definition: 'weather', hsk_level: 3 },
  { character: '条', pinyin: 'tiao2', english_definition: 'measure word for long thin objects', hsk_level: 3 },
  { character: '同意', pinyin: 'tong2 yi4', english_definition: 'to agree; to consent', hsk_level: 3 },
  { character: '头发', pinyin: 'tou2 fa', english_definition: 'hair (on head)', hsk_level: 3 },
  { character: '完成', pinyin: 'wan2 cheng2', english_definition: 'to complete; to accomplish', hsk_level: 3 },
  { character: '味道', pinyin: 'wei4 dao', english_definition: 'taste; flavor', hsk_level: 3 },
  { character: '文章', pinyin: 'wen2 zhang1', english_definition: 'article; essay', hsk_level: 3 },
  { character: '问候', pinyin: 'wen4 hou4', english_definition: 'to greet; greeting', hsk_level: 3 },
  { character: '洗澡', pinyin: 'xi3 zao3', english_definition: 'to take a shower/bath', hsk_level: 3 },
  { character: '先后', pinyin: 'xian1 hou4', english_definition: 'in order; successively', hsk_level: 3 },
  { character: '相同', pinyin: 'xiang1 tong2', english_definition: 'identical; same', hsk_level: 3 },
  { character: '相信', pinyin: 'xiang1 xin4', english_definition: 'to believe; to trust', hsk_level: 3 },
  { character: '小吃', pinyin: 'xiao3 chi1', english_definition: 'snack', hsk_level: 3 },
  { character: '效果', pinyin: 'xiao4 guo3', english_definition: 'effect; result', hsk_level: 3 },
  { character: '新鲜', pinyin: 'xin1 xian1', english_definition: 'fresh', hsk_level: 3 },
  { character: '兴趣', pinyin: 'xing4 qu4', english_definition: 'interest (in something)', hsk_level: 3 },
  { character: '行', pinyin: 'xing2', english_definition: 'okay; to be all right', hsk_level: 3 },
  { character: '许多', pinyin: 'xu3 duo1', english_definition: 'many; a lot of', hsk_level: 3 },
  { character: '学期', pinyin: 'xue2 qi1', english_definition: 'semester; school term', hsk_level: 3 },
  { character: '研究', pinyin: 'yan2 jiu1', english_definition: 'to research; research', hsk_level: 3 },
  { character: '阳台', pinyin: 'yang2 tai1', english_definition: 'balcony', hsk_level: 3 },
  { character: '要是', pinyin: 'yao4 shi', english_definition: 'if', hsk_level: 3 },
  { character: '也许', pinyin: 'ye3 xu3', english_definition: 'perhaps; maybe', hsk_level: 3 },
  { character: '以', pinyin: 'yi3', english_definition: 'to; by; with', hsk_level: 3 },
  { character: '以后', pinyin: 'yi3 hou4', english_definition: 'after; later', hsk_level: 3 },
  { character: '意思', pinyin: 'yi4 si', english_definition: 'meaning', hsk_level: 3 },
  { character: '因此', pinyin: 'yin1 ci3', english_definition: 'therefore; consequently', hsk_level: 3 },
  { character: '有名', pinyin: 'you3 ming2', english_definition: 'famous', hsk_level: 3 },
  { character: '有意思', pinyin: 'you3 yi4 si', english_definition: 'interesting', hsk_level: 3 },
  { character: '于是', pinyin: 'yu2 shi4', english_definition: 'thereupon; hence', hsk_level: 3 },
  { character: '语法', pinyin: 'yu3 fa3', english_definition: 'grammar', hsk_level: 3 },
  { character: '元旦', pinyin: 'yuan2 dan4', english_definition: "New Year's Day", hsk_level: 3 },
  { character: '愿意', pinyin: 'yuan4 yi4', english_definition: 'to be willing', hsk_level: 3 },
  { character: '月饼', pinyin: 'yue4 bing3', english_definition: 'mooncake', hsk_level: 3 },
  { character: '阅读', pinyin: 'yue4 du2', english_definition: 'to read; reading', hsk_level: 3 },
  { character: '整理', pinyin: 'zheng3 li3', english_definition: 'to sort out; to organize', hsk_level: 3 },
  { character: '正常', pinyin: 'zheng4 chang2', english_definition: 'normal', hsk_level: 3 },
  { character: '之后', pinyin: 'zhi1 hou4', english_definition: 'after; afterwards', hsk_level: 3 },
  { character: '之前', pinyin: 'zhi1 qian2', english_definition: 'before; prior', hsk_level: 3 },
  { character: '知识', pinyin: 'zhi1 shi', english_definition: 'knowledge', hsk_level: 3 },
  { character: '直接', pinyin: 'zhi2 jie1', english_definition: 'direct; directly', hsk_level: 3 },
  { character: '终于', pinyin: 'zhong1 yu2', english_definition: 'finally; at last', hsk_level: 3 },
  { character: '周围', pinyin: 'zhou1 wei2', english_definition: 'surroundings; around', hsk_level: 3 },
  { character: '主要', pinyin: 'zhu3 yao4', english_definition: 'main; principal', hsk_level: 3 },
  { character: '准备', pinyin: 'zhun3 bei4', english_definition: 'to prepare; preparation', hsk_level: 3 },
  { character: '自己', pinyin: 'zi4 ji3', english_definition: 'oneself; self', hsk_level: 3 },
  { character: '总是', pinyin: 'zong3 shi4', english_definition: 'always', hsk_level: 3 },
  { character: '走路', pinyin: 'zou3 lu4', english_definition: 'to walk', hsk_level: 3 },
  { character: '最后', pinyin: 'zui4 hou4', english_definition: 'final; last; at last', hsk_level: 3 },
  { character: '最近', pinyin: 'zui4 jin4', english_definition: 'recently; lately', hsk_level: 3 },
  { character: '作者', pinyin: 'zuo4 zhe3', english_definition: 'author; writer', hsk_level: 3 },

  // ========== HSK 4 (sample) ==========
  { character: '语言学', pinyin: 'yu3 yan2 xue2', english_definition: 'linguistics', hsk_level: 4 },
  { character: '互联网', pinyin: 'hu4 lian2 wang3', english_definition: 'internet', hsk_level: 4 },
  { character: '社会', pinyin: 'she4 hui4', english_definition: 'society', hsk_level: 4 },
  { character: '经济', pinyin: 'jing1 ji4', english_definition: 'economy; economics', hsk_level: 4 },
  { character: '文化', pinyin: 'wen2 hua4', english_definition: 'culture', hsk_level: 4 },
  { character: '政治', pinyin: 'zheng4 zhi4', english_definition: 'politics', hsk_level: 4 },
  { character: '科学', pinyin: 'ke1 xue2', english_definition: 'science', hsk_level: 4 },
  { character: '技术', pinyin: 'ji4 shu4', english_definition: 'technology; skill', hsk_level: 4 },
  { character: '环境', pinyin: 'huan2 jing4', english_definition: 'environment', hsk_level: 4 },
  { character: '污染', pinyin: 'wu1 ran3', english_definition: 'pollution', hsk_level: 4 },
  { character: '交通', pinyin: 'jiao1 tong1', english_definition: 'transportation; traffic', hsk_level: 4 },
  { character: '医疗', pinyin: 'yi1 liao2', english_definition: 'medical treatment', hsk_level: 4 },
  { character: '教育', pinyin: 'jiao4 yu4', english_definition: 'education', hsk_level: 4 },
  { character: '历史', pinyin: 'li4 shi3', english_definition: 'history', hsk_level: 4 },
  { character: '地理', pinyin: 'di4 li3', english_definition: 'geography', hsk_level: 4 },
  { character: '数学', pinyin: 'shu4 xue2', english_definition: 'mathematics', hsk_level: 4 },
  { character: '物理', pinyin: 'wu4 li3', english_definition: 'physics', hsk_level: 4 },
  { character: '化学', pinyin: 'hua4 xue2', english_definition: 'chemistry', hsk_level: 4 },
  { character: '生物', pinyin: 'sheng1 wu4', english_definition: 'biology; living things', hsk_level: 4 },
  { character: '哲学', pinyin: 'zhe2 xue2', english_definition: 'philosophy', hsk_level: 4 },
  { character: '心理', pinyin: 'xin1 li3', english_definition: 'psychology; mentality', hsk_level: 4 },
  { character: '法律', pinyin: 'fa3 lv4', english_definition: 'law', hsk_level: 4 },
  { character: '建筑', pinyin: 'jian4 zhu4', english_definition: 'building; architecture', hsk_level: 4 },
  { character: '艺术', pinyin: 'yi4 shu4', english_definition: 'art', hsk_level: 4 },
  { character: '音乐', pinyin: 'yin1 yue4', english_definition: 'music', hsk_level: 4 },
  { character: '舞蹈', pinyin: 'wu3 dao3', english_definition: 'dance', hsk_level: 4 },
  { character: '体育', pinyin: 'ti3 yu4', english_definition: 'physical education; sports', hsk_level: 4 },
  { character: '运动', pinyin: 'yun4 dong4', english_definition: 'sports; exercise; movement', hsk_level: 4 },
  { character: '竞争', pinyin: 'jing4 zheng1', english_definition: 'competition', hsk_level: 4 },
  { character: '合作', pinyin: 'he2 zuo4', english_definition: 'cooperation; to cooperate', hsk_level: 4 },
  { character: '发展', pinyin: 'fa1 zhan3', english_definition: 'development; to develop', hsk_level: 4 },
  { character: '进步', pinyin: 'jin4 bu4', english_definition: 'progress; improvement', hsk_level: 4 },
  { character: '改变', pinyin: 'gai3 bian4', english_definition: 'to change', hsk_level: 4 },
  { character: '影响', pinyin: 'ying3 xiang3', english_definition: 'influence; effect', hsk_level: 4 },
  { character: '解决', pinyin: 'jie3 jue2', english_definition: 'to solve; to resolve', hsk_level: 4 },
  { character: '讨论', pinyin: 'tao3 lun4', english_definition: 'to discuss; discussion', hsk_level: 4 },
  { character: '分析', pinyin: 'fen1 xi1', english_definition: 'to analyze; analysis', hsk_level: 4 },
  { character: '研究', pinyin: 'yan2 jiu1', english_definition: 'to research; research', hsk_level: 4 },
  { character: '计划', pinyin: 'ji4 hua4', english_definition: 'plan; to plan', hsk_level: 4 },
  { character: '目标', pinyin: 'mu4 biao1', english_definition: 'goal; target; objective', hsk_level: 4 },
  { character: '成功', pinyin: 'cheng2 gong1', english_definition: 'success; to succeed', hsk_level: 4 },
  { character: '失败', pinyin: 'shi1 bai4', english_definition: 'failure; to fail', hsk_level: 4 },
  { character: '经验', pinyin: 'jing1 yan4', english_definition: 'experience', hsk_level: 4 },
  { character: '机会', pinyin: 'ji1 hui4', english_definition: 'opportunity; chance', hsk_level: 4 },
  { character: '挑战', pinyin: 'tiao3 zhan4', english_definition: 'challenge; to challenge', hsk_level: 4 },
  { character: '压力', pinyin: 'ya1 li4', english_definition: 'pressure; stress', hsk_level: 4 },
  { character: '健康', pinyin: 'jian4 kang1', english_definition: 'health; healthy', hsk_level: 4 },
  { character: '幸福', pinyin: 'xing4 fu2', english_definition: 'happiness; happy', hsk_level: 4 },
  { character: '自由', pinyin: 'zi4 you2', english_definition: 'freedom; free', hsk_level: 4 },
  { character: '平等', pinyin: 'ping2 deng3', english_definition: 'equality; equal', hsk_level: 4 },
  { character: '责任', pinyin: 'ze2 ren4', english_definition: 'responsibility; duty', hsk_level: 4 },
  { character: '义务', pinyin: 'yi4 wu4', english_definition: 'obligation; duty', hsk_level: 4 },
  { character: '权利', pinyin: 'quan2 li4', english_definition: 'right (entitlement)', hsk_level: 4 },
]
