export const PINYIN_SYLLABLES = new Set([
  'bi', 'pi', 'mi', 'di', 'ti', 'ni', 'li', 'ji', 'qi', 'xi',
  'zhi', 'chi', 'shi', 'ri', 'zi', 'ci', 'si', 'yi', 'wu', 'yu',
  'nv', 'lv', 'nü', 'lü',
  'ba', 'pa', 'ma', 'fa', 'da', 'ta', 'na', 'la', 'ga', 'ka', 'ha', 'za', 'ca', 'sa', 'zha', 'cha', 'sha',
  'bo', 'po', 'mo', 'fo', 'lo',
  'be', 'pe', 'me', 'fe', 'de', 'te', 'ne', 'le', 'ge', 'ke', 'he', 'ze', 'ce', 'se', 'zhe', 'che', 'she', 're',
  'bai', 'pai', 'mai', 'dai', 'tai', 'nai', 'lai', 'gai', 'kai', 'hai', 'zai', 'cai', 'sai', 'zhai', 'chai', 'shai',
  'bei', 'pei', 'mei', 'fei', 'dei', 'tei', 'nei', 'lei', 'gei', 'kei', 'hei', 'zei', 'cei', 'shei', 'zhei',
  'bao', 'pao', 'mao', 'dao', 'tao', 'nao', 'lao', 'gao', 'kao', 'hao', 'zao', 'cao', 'sao', 'zhao', 'chao', 'shao', 'rao',
  'pou', 'mou', 'fou', 'dou', 'tou', 'nou', 'lou', 'gou', 'kou', 'hou', 'zou', 'cou', 'sou', 'zhou', 'chou', 'shou', 'rou',
  'ban', 'pan', 'man', 'fan', 'dan', 'tan', 'nan', 'lan', 'gan', 'kan', 'han', 'zan', 'can', 'san', 'zhan', 'chan', 'shan', 'ran',
  'ben', 'pen', 'men', 'fen', 'den', 'nen', 'gen', 'ken', 'hen', 'zen', 'cen', 'sen', 'zhen', 'chen', 'shen', 'ren',
  'bin', 'pin', 'min', 'nin', 'lin',
  'bang', 'pang', 'mang', 'fang', 'dang', 'tang', 'nang', 'lang', 'gang', 'kang', 'hang', 'zang', 'cang', 'sang', 'zhang', 'chang', 'shang', 'rang',
  'beng', 'peng', 'meng', 'feng', 'deng', 'teng', 'neng', 'leng', 'geng', 'keng', 'heng', 'zeng', 'ceng', 'seng', 'zheng', 'cheng', 'sheng', 'reng',
  'bing', 'ping', 'ming', 'ding', 'ting', 'ning', 'ling',
  'biao', 'piao', 'miao', 'diao', 'tiao', 'niao', 'liao', 'jiao', 'qiao', 'xiao',
  'bian', 'pian', 'mian', 'dian', 'tian', 'nian', 'lian', 'jian', 'qian', 'xian',
  'bie', 'pie', 'mie', 'die', 'tie', 'nie', 'lie', 'jie', 'qie', 'xie',
  'bu', 'pu', 'mu', 'fu', 'du', 'tu', 'nu', 'lu', 'gu', 'ku', 'hu', 'zu', 'cu', 'su', 'zhu', 'chu', 'shu', 'ru',
  'duo', 'tuo', 'nuo', 'luo', 'guo', 'kuo', 'huo', 'ruo', 'zuo', 'cuo', 'suo', 'zhuo', 'chuo', 'shuo',
  'dui', 'tui', 'gui', 'kui', 'hui', 'zui', 'cui', 'sui', 'zhui', 'chui', 'shui', 'rui',
  'dun', 'tun', 'nun', 'lun', 'gun', 'kun', 'hun', 'zun', 'cun', 'sun', 'zhun', 'chun', 'shun', 'run',
  'dong', 'tong', 'nong', 'long', 'gong', 'kong', 'hong', 'rong', 'zong', 'cong', 'song', 'zhong', 'chong',
  'duan', 'tuan', 'nuan', 'luan', 'guan', 'kuan', 'huan', 'zuan', 'cuan', 'suan', 'zhuan', 'chuan', 'shuan', 'ruan',
  'gua', 'kua', 'hua', 'zhua', 'chua', 'shua',
  'guai', 'kuai', 'huai', 'zhuai', 'chuai', 'shuai',
  'guang', 'kuang', 'huang', 'zhuang', 'chuang', 'shuang',
  'geng', 'keng', 'heng',
  'gong', 'kong', 'hong', 'rong', 'zhong', 'chong',
  'gang', 'kang', 'hang', 'zhang', 'chang', 'shang', 'rang', 'zang', 'cang', 'sang',
  'ga', 'ka', 'ha', 'zha', 'cha', 'sha',
  'ge', 'ke', 'he', 'zhe', 'che', 'she', 're', 'ze', 'ce', 'se',
  'ji', 'qi', 'xi',
  'jia', 'qia', 'xia',
  'jie', 'qie', 'xie',
  'jiao', 'qiao', 'xiao',
  'jiu', 'qiu', 'xiu',
  'jian', 'qian', 'xian',
  'jin', 'qin', 'xin',
  'jiang', 'qiang', 'xiang',
  'jing', 'qing', 'xing',
  'jiong', 'qiong', 'xiong',
  'juan', 'quan', 'xuan',
  'jun', 'qun', 'xun',
  'jue', 'que', 'xue',
  'ju', 'qu', 'xu',
  'niao', 'liao',
  'nian', 'lian',
  'niang', 'liang',
  'ning', 'ling',
  'niu', 'liu',
  'nie', 'lie',
  'nu', 'lu', 'nü', 'lü', 'nv', 'lv',
  'nuan', 'luan',
  'nuo', 'luo',
  'nun', 'lun',
  'neng', 'leng',
  'nang', 'lang',
  'nen', 'len',
  'nan', 'lan',
  'nao', 'lao',
  'nai', 'lai',
  'nei', 'lei',
  'nou', 'lou',
  'nong', 'long',
  'ao', 'ou', 'an', 'en', 'ang', 'eng', 'er', 'ai', 'ei',
  'wa', 'wo', 'wai', 'wei', 'wan', 'wen', 'wang', 'weng',
  'ya', 'yo', 'ye', 'yao', 'you', 'yan', 'yin', 'yang', 'ying', 'yong',
  'yue', 'yun', 'yuan',
])
